create table if not exists links_maillage (
   id             bigint
      generated by default as identity
   primary key,
   id_link        bigint,
   categ_name     varchar,
   url            varchar not null,
   anchor_text    varchar not null,
   level_number   int,
   parent_link_id bigint,
   score          int,
   root_context   varchar,
   createat       date
);
create table if not exists rules (
   id_rule                   bigint
      generated by default as identity
   primary key,
   support_url_pattern       varchar,
   support_page_type_pattern varchar,
   nature                    varchar null,
   max_links_number          int,
   nb_column                 int not null,
   insertion_method          varchar not null,
   ancestor_categ_id         int not null,
   root_context              varchar null,
   support_block_name        varchar null,
   support_block_location    varchar not null,
   priority_score            int null,
   start_level               int null,
   auth_depth                int null,
   score_min                 int null,
   createat                  date
);

create table if not exists log (
   id          bigint
      generated by default as identity
   primary key,
   action      varchar(255) not null,
   description text,
   version_id  int,
   created_at  timestamp default now()
);

create table if not exists sys_option (
   id        bigint
      generated by default as identity
   primary key,
   data_json json not null,
   createat  timestamp default current_timestamp
);